### ISSUE TITLE
libleptonica-1.78.0.so no longer being bundled with SmiServices releases

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1226] opened 2022-07-19 11:32 UTC
I think this has occurred since the refactoring of IsIdentifiable to its own package. Seems like only the Windows DLLs are being packaged now.

Any ideaas @howff @tznind ?

**Comment by tznind** [comment] 2022-07-19 11:51
It is in the csproj
```
thomas@thomas-CF-31WBLAHLM:~/IsIdentifiable$ git grep  libleptonica
IsIdentifiable/IsIdentifiable.csproj:    <Content Include="lib\libleptonica.so.1.78.0-minimal-centos7" Link="x64\libleptonica-1.78.0.so">
IsIdentifiable/IsIdentifiable.csproj:    <Content Include="lib\libleptonica.so.1.78.0-minimal-centos7" Link="x64\libleptonica.so.5.3.0">
Binary file IsIdentifiable/lib/libleptonica.so.1.78.0-minimal-centos7 matches
Binary file IsIdentifiable/lib/libtesseract.so.4.0.1-centos7 matches
```

Also seems to be in the nupkg
```
thomas@thomas-CF-31WBLAHLM:~/Downloads/deleteme$ unzip ./isidentifiable.0.0.4.nupkg
Archive:  ./isidentifiable.0.0.4.nupkg
  inflating: _rels/.rels             
  inflating: IsIdentifiable.nuspec   
  inflating: lib/netstandard2.1/Rules.template.yaml  
  inflating: lib/netstandard2.1/x86/tesseract41.dll  
  inflating: lib/netstandard2.1/x86/leptonica-1.78.0.dll  
  inflating: lib/netstandard2.1/IsIdentifiable.dll  
  inflating: lib/netstandard2.1/x64/libleptonica.so.5.3.0  
  inflating: lib/netstandard2.1/NuGet.deps.json  
  inflating: lib/netstandard2.1/x64/tesseract41.dll  
  inflating: lib/netstandard2.1/NuGet.dll  
  inflating: lib/netstandard2.1/x64/leptonica-1.78.0.dll  
  inflating: lib/netstandard2.1/x64/libleptonica-1.78.0.so  
  inflating: lib/netstandard2.1/IsIdentifiable.xml  
  inflating: lib/netstandard2.1/x64/libtesseract41.so  
  inflating: [Content_Types].xml     
  inflating: package/services/metadata/core-properties/a0b6f42e75044c1186278b1743be4720.psmdcp  
 extracting: .signature.p7s          

```

**Comment by rkm** [comment] 2022-07-19 13:21
Looks as if the x86/x64 files published with SmIServices come from the tesseract dependency and not our bundled files from IsIdentifiable.

**Comment by rkm** [comment] 2022-07-19 13:24
In IsIdentifiable we probably want to do something like [this](https://github.com/charlesw/tesseract/blob/master/src/Tesseract/Tesseract.csproj#L54-L56):

```csproj
<Content Include="x64\*" Pack="true" PackageCopyToOutput="true" PackagePath="x64">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
<Content Include="x86\*" Pack="true" PackageCopyToOutput="true" PackagePath="x86">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

**Comment by rkm** [comment] 2022-07-19 13:51
Yeah it doesn't seem like any of the content assets from IsIdentifiable are being pulled into SmIServices.

That's all the digging I have time for just now. Have solved this on the live system in the meantime by copying the files from the old release.

**Comment by tznind** [comment] 2022-07-20 08:25
Ok here is a repro, I can confirm that running on linux the files are not shipped.

```
cd ~
rm -rfd hello
dotnet new console -n hello
cd hello
dotnet add package IsIdentifiable
dotnet publish -r linux-x64

find . -name *.so
```

**Comment by tznind** [comment] 2022-07-20 08:36
> In IsIdentifiable we probably want to do something like [this](https://github.com/charlesw/tesseract/blob/master/src/Tesseract/Tesseract.csproj#L54-L56):


Yup I think thats what we need

**Comment by tznind** [comment] 2022-07-20 09:06
This should be the fix https://github.com/SMI/IsIdentifiable/pull/116

@rkm can you confirm that your workaround put the .so files into the x64 directory?

**Comment by rkm** [comment] 2022-08-19 08:59
Just checked this now with IsIdentifiable v0.0.6 and it doesn't seem the so files are being copied to the output

**Comment by tznind** [comment] 2022-08-19 10:41
How annoying, ok I've added it to the Mirror board for visibility https://github.com/orgs/HicServices/projects/5/views/1

**Comment by tznind** [comment] 2022-08-19 11:12
Ok seems like we might need to specifically set `<PackagePath>` to `content` and not just `x64` as was done in https://github.com/SMI/IsIdentifiable/pull/116

See:
- https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#including-content-in-a-package
- https://stackoverflow.com/a/49438592/4824531
- https://github.com/NuGet/Home/issues/10906#issuecomment-864411935

**Comment by tznind** [comment] 2022-08-19 12:09
Ok so `IsIdentifiable` has the following, some of which comes from tesseract and some don't:

![image](https://user-images.githubusercontent.com/31306100/185614307-9b5c96ad-8343-4686-a6e2-3612317a509e.png)

IsIdentifiable's Tesseract dependency looks like this:

![image](https://user-images.githubusercontent.com/31306100/185614180-f1662193-5afe-4b03-b30c-bd34b6847183.png)

The `Tesseract.targets` file has the following in it:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)\..\x86\leptonica-1.78.0.dll">
            <Link>x86\leptonica-1.78.0.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="$(MSBuildThisFileDirectory)\..\x86\tesseract41.dll">
            <Link>x86\tesseract41.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="$(MSBuildThisFileDirectory)\..\x64\leptonica-1.78.0.dll">
            <Link>x64\leptonica-1.78.0.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="$(MSBuildThisFileDirectory)\..\x64\tesseract41.dll">
            <Link>x64\tesseract41.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
```

From what I remember we have manually built `libleptonica.so.1.78.0-minimal-centos7`, `libleptonica-1.78.0.so` and `libtesseract.so.4.0.1-centos7`.

The current logic in `IsIdentifiable` is the below.  This works for a ProjectReference (from `ii`) but not via Nuget

```xml
<ItemGroup>
    <Content Include="lib\libtesseract.so.4.0.1-centos7" Link="x64\libtesseract41.so" Pack="true" PackageCopyToOutput="true" PackagePath="x64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\libleptonica.so.1.78.0-minimal-centos7" Link="x64\libleptonica-1.78.0.so" Pack="true" PackageCopyToOutput="true" PackagePath="x64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="lib\libleptonica.so.1.78.0-minimal-centos7" Link="x64\libleptonica.so.5.3.0" Pack="true" PackageCopyToOutput="true" PackagePath="x64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Rules.template.yaml" Pack="true" PackageCopyToOutput="true">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

@rkm what files are you copying to what directories in order to make the SmiServices IsIdentifiable work again?  Are you copying them from the IsIdentifiable nuget package (i.e. the lib dir) or somewhere else?

**Comment by tznind** [comment] 2022-08-19 12:15
Based on the csproj file above we seem to be copying `libleptonica.so.1.78.0-minimal-centos7` to both `x64\libleptonica-1.78.0.so` and `libleptonica.so.5.3.0` which is confusing to me and feels very hacky.  If its 1.7.8 how can it also be 5.3.0 😕

**Comment by jas88** [comment] 2022-08-19 14:09
Latest is 1.82.0 so no idea where charlesw is getting the "5.3.0" bit... ¯\_(ツ)_/¯

**Comment by howff** [comment] 2022-08-19 16:38
leptonica is an internal dependency of tesseract so the version will be whatever was available when it was compiled. Why there's two versions is a mystery to me, unless it's because the charlesw/tesseract package also has a dependency on leptonica but using a different numbering scheme. I think the way we discovered what filenames were required was to trace the executable looking for open() calls which failed. Right now I think the question is not why, but how to get them copied!

**Comment by jas88** [comment] 2022-08-22 21:38
Fixed in PR in IsIdentifiable along with an update to a release build rather than a beta. (The 5.3.0 seems to have been an oddity inserted by CentOS when packaging the libraries for distribution - no longer present in IsIdentifiable.)

**Comment by tznind** [comment] 2022-08-23 07:24
That's great @jas88 thanks, is that https://github.com/SMI/IsIdentifiable/pull/4 and is it ready for review and merge?

**Comment by jas88** [comment] 2022-08-23 15:49
@tznind Yep, all set!

**Comment by jas88** [comment] 2024-06-04 21:47
Fix upstream in https://github.com/SMI/IsIdentifiable#4

**Closed by jas88** 2024-06-04 21:47 UTC
Labels: bug
